<div id="outline_div" class="width800 viewcolor">
	<div id="topic-toolbar">
		<?php echo $this->topicToolbar('outline',$this->id); ?>
	</div>
	<h2><?php echo $this->title; ?></h2>
	<div id="outline-view">
		<?php echo $this->content; ?>	
	</div>
	<div id="outline-entries">
		<?php foreach ($this->entries as $num => $entries)
		  {
		      $title = $entries['title'];
		      $description = $entries['description'];
		      $id = $entries['id'];
		      $key2 = $entries['key'];
		?>
		<div>
			<?php echo $title ?>
			<?php echo $description ?>
			<ul class="outline_tools edit_off">
				<li>
					<a href="#" onclick="editOutlineEntry(<?php echo $this->id; ?>,<?php echo $key2 ?>)">Edit</a>
					<a href="#" onclick="addOutlineEntry(<?php echo $this->id; ?>,<?php echo $key2 ?>)">Add</a>
					<a href="#" onclick="upOutlineEntry(<?php echo $this->id; ?>,<?php echo $key2 ?>)">Up</a>
					<a href="#" onclick="downOutlineEntry(<?php echo $this->id; ?>,<?php echo $key2 ?>)">Down</a>
					<a href="#" onclick="deleteOutlineEntry(<?php echo $this->id; ?>,<?php echo $key2 ?>)">Delete</a>
				</li>
			</ul>
			<div id="outline-entry-<?php echo $id; ?>-<?php echo $key2; ?>">
				<div>
					<span><?php echo $key2; ?></span>
					<textarea id="outline-entry-view-<?php echo $id; ?>-<?php echo $key; ?>-<?php echo $key2; ?>"><?php echo $title; ?></textarea>
					<textarea id="outline-entry-edit-<?php echo $id; ?>-<?php echo $key; ?>-<?php echo $key2;?>" class="edit_off"><?php echo $description; ?></textarea>
				</div>
			</div>
		</div>
		<?php
			}
		?>
	</div>
	<div id="outline-edit" class="hidden">
    		<textarea id="outline-edit-textarea" rows="24" cols="200"><?php echo $this->content; ?></textarea>
	</div>
</div>
