<div>
	<h2>Content</h2>
	<?php
	    echo $this->form()->openTag($form);
	    echo $this->formHidden($form->get('id'));
	    echo $this->formHidden($form->get('username'));
            echo $this->formRow($form->get('original_date'));
            echo $this->formRow($form->get('verbage'));
            echo $this->formRow($form->get('columnSize'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
	?>
</div>
