<div style="background-color:<?php echo $this->bcolor;?>" id="file-<?php echo $this->id;?>">
    <h2>CodeBase - <?php echo $this->title; ?></h2>
    <div>
	<span>Code Base</span>
	<span>FileID: <?php echo $this->fileid; ?></span>
	<span><?php echo $this->title; ?></span>
	<span><?php echo $this->author; ?></span>
	<span><?php echo $this->description; ?></span>
	<span><?php echo $this->fileContents; ?></span>
    </div>
</div>
