<div style="background-color:<?php echo $this->bcolor;?>" class="headline-item" id="headline-<?php echo $this->id;?>">
    <h2><?php echo $this->title; ?></h2>
    <div class="headline-item-title">
        <span><a href="/headline/view/<?php echo $this->id; ?>">Edit</a></span>
        <span><a href="/headline/delete/<?php echo $this->id; ?>">Delete</a></span>
	<br />
        <span><?php echo $this->original;?></span>
    </div>
    <div class="headline-item-text" onclick="clickHeadlineItemText('headline-<?php echo $this->id;?>')">
    	<span><?php echo $this->headline; ?></span>
    </div>
</div>
