<div>
	<h2>Content</h2>
	<?php
	    echo print_r($this->messages,true);
	    echo print_r($this->service,true);
	    echo $this->form()->openTag($form);
	    echo $this->formHidden($form->get('id'));
        ?>
	<br/>
	<h2>Username</h2>
        <?php
            echo $this->formRow($form->get('username'));
        ?>
	<br/>
	<h2>Password</h2>
        <?php
            echo $this->formRow($form->get('password'));
        ?>
	<br/>
	<h2>Remember Me!</h2>
        <?php
            echo $this->formRow($form->get('rememberme'));
        ?>
	<br/>
	<?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
	?>
</div>
