<div>
	<h2>Content</h2>
	<?php
	    foreach ($this->messages as $key => $value)
            {
		echo "<h4 style='color:red'>$value</h4>";
		echo "<br/>";
	    }
	    echo $this->form()->openTag($form);
	    echo $this->formHidden($form->get('id'));
        ?>
	<br/>
	<h2>Username</h2>
        <?php
            echo $this->formRow($form->get('username'));
        ?>
	<br/>
	<h2>Password</h2>
        <?php
            echo $this->formRow($form->get('password'));
        ?>
	<br/>
	<h2>Remember Me!</h2>
        <?php
            echo $this->formRow($form->get('rememberme'));
        ?>
	<br/>
	<?php
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
	?>
</div>
