Article:
    type: entity
    table: Article
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        columnsize:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: columnSize
        verbage:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
