Broadsheet:
    type: entity
    table: Broadsheet
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pageno:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pageNo
        pagewidth:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pageWidth
        pageheight:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: pageHeight
    lifecycleCallbacks: {  }
