Correspondant:
    type: entity
    table: Correspondant
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        handle:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        wordage:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        picture:
            type: blob
            nullable: false
            length: null
            fixed: false
            comment: ''
        width:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        height:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
