Headline:
    type: entity
    table: Headline
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        width:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        height:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        gluex:
            type: boolean
            nullable: false
            comment: ''
        gluey:
            type: boolean
            nullable: false
            comment: ''
        prevx:
            type: boolean
            nullable: false
            comment: ''
        prevy:
            type: boolean
            nullable: false
            comment: ''
        resetx:
            type: boolean
            nullable: false
            comment: ''
        resety:
            type: boolean
            nullable: false
            comment: ''
        drift:
            type: boolean
            nullable: false
            comment: ''
        gravity:
            type: boolean
            nullable: false
            comment: ''
        offsetx:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        offsety:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        headline:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        topline:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        usetopline:
            type: boolean
            nullable: false
            comment: ''
        fontsize:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        headlineclass:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        italic:
            type: boolean
            nullable: false
            comment: ''
    lifecycleCallbacks: {  }
