Pix:
    type: entity
    table: Pix
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: text 
            nullable: false
            length: 255
            fixed: false
            comment: ''
        original_date:
            type: date
            nullable: false
            comment: ''
        title:
            type: text
            nullable: false
            length: 255
            fixed: false
            comment: ''
        caption:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        credit:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        picture:
            type: blob
            nullable: false
            length: null
            fixed: false
            comment: ''
        width:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        height:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
