Wordage:
    type: entity
    table: wordage
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        wordage:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
        columnsize:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: columnSize
        title:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
