Wordage:
    type: entity
    table: Wordage
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: text 
            nullable: false
            length: 255
            fixed: false
            comment: ''
        original_date:
            type: date
            nullable: false
            comment: ''
        title:
            type: text
            nullable: false
            length: 255
            fixed: false
            comment: ''
        wordage:
            type: text 
            nullable: false
            length: 255
            fixed: false
            comment: ''
        columnsize:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: columnSize
    lifecycleCallbacks: {  }
