<div id="experience_div" class="width800 viewcolor">
		<div id="experience-form-fields">
			<h2>Experience - Edit Form</h2>
			<span>Description</span>
			<input type="text" name="description" value="<?php echo $this->content; ?>">
			<br/>
			<span>Skills</span>
			<input type="text" name="skills" value="<?php echo $this->skills; ?>">
			<br/>
			<span>Role</span>
			<input type="text" name="role" value="<?php echo $this->role; ?>">
			<br/>
			<span>Company</span>
			<input type="text" name="company" value="<?php echo $this->company; ?>">
			<br/>
			<span>Title</span>
			<input type="text" name="title" value="<?php echo $this->title; ?>">
			<br/>
			<span>Start Date</span>
			<input type="text" name="startDate" value="<?php echo $this->startDate; ?>">
			<br/>
			<span>End Date</span>
			<input type="text" name="endDate" value="<?php echo $this->endDate; ?>">
			<br/>
		</div>
</div>
