<div id="experience_div" class="width800 viewcolor">
	<div id="topic-toolbar">
		<?php echo $this->topicToolbar('experience',$this->id,'default'); ?>
	</div>

	<h2><?php echo $this->title; ?></h2>
	
	<div id="experience-view">
		<h2>Experience - Edit Form</h2>
		<span>Description</span>
		<span id="description-view"><?php echo $this->content; ?></span>
		<br/>
		<span>Skills</span>
		<span id="skills-view"><?php echo $this->skills; ?></span>
		<br/>
		<span>Role</span>
		<span id="role-view"><?php echo $this->role; ?></span>
		<br/>
		<span>Company</span>
		<span id="company-view"><?php echo $this->company; ?></span>
		<br/>
		<span>Title</span>
		<span id="title-view"><?php echo $this->title; ?></span>
		<br/>
		<span>Start Date</span>
		<span id="startDate-view"><?php echo $this->startDate; ?></span>
		<br/>
		<span>End Date</span>
		<span id="endDate-view"><?php echo $this->endDate; ?></span>
	</div>

	<div id="experience-edit" class="width800 viewcolor">
		<div id="experience-form-fields">
			<h2>Experience - Edit Form</h2>
			<span>Description</span>
			<input type="text" name="description" value="<?php echo $this->content; ?>">
			<br/>
			<span>Skills</span>
			<input type="text" name="skills" value="<?php echo $this->skills; ?>">
			<br/>
			<span>Role</span>
			<input type="text" name="role" value="<?php echo $this->role; ?>">
			<br/>
			<span>Company</span>
			<input type="text" name="company" value="<?php echo $this->company; ?>">
			<br/>
			<span>Title</span>
			<input type="text" name="title" value="<?php echo $this->title; ?>">
			<br/>
			<span>Start Date</span>
			<input type="text" name="startDate" value="<?php echo $this->startDate; ?>">
			<br/>
			<span>End Date</span>
			<input type="text" name="endDate" value="<?php echo $this->endDate; ?>">
			<br/>
		</div>
	</div>
</div>
