<!DOCTYPE html>
<!-- saved from url=(0026)https://www.evtechnote.us/ -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Home</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="/css/styles.css" type="text/css" rel="stylesheet">
    <link href="/css/nhp.css" type="text/css" rel="stylesheet">
    <!-- development version, includes helpful console warnings -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=a6a0g2hrxjm58bb5cysjzf6jgugbqf7l9u3m8hfjkdj3mkg7"></script> 
    <script src="/js/nhpress.js"></script>
    <script>tinymce.init({selector: '#wordage-edit-textarea'});</script>
 </head>
<body class="body_class">
    <div id="main-bar" class="evtechnote-color-1">
    	<ul>
		<?php echo print_r($this->layout()->site_toolbar,true) ?>
		<?php echo print_r($this->layout()->user_toolbar,true) ?>
       </ul>
    </div>
    <div id="main-header" class="evtechnote-color-2">
      <div id="menu-crumbs" onclick="showMenu();"><img src="./Home_files/menu.png"></div>
      <!-- Unnamed (Shape) -->
      <div id="top-bar" class="evtechnote-color-2"> 
          <div id="masthead">
		      <div id="binder_note">
				<span>BINDER NAME HERE</span>
				<span>binder selectors</span>
				<span>Add New Binder</span>
		      </div>
		      <div id="issue_date">
				  <span class="issue_date_text"><?php echo date("F j, Y");  ?>&nbsp;&nbsp;</span>
			  </div>
              <h1>&nbsp;&nbsp;evtechnote.us</h1>
			  <h4><i>&quot;Covering the Internet and Internet Technology&quot;</i></h4>
			  <br/>
		  </div>
		</div>
	</div>
	<div id="main-page">
	  <div id="main-toolbar">
		<span>Main Toolbar</span>
	  </div>
          <div id="content" class="evtechnote-color-2-">
		<?php echo $this->content; ?>
          </div>
    </div>
    <div id="main-footer" class="evtechnote-color-1">
	<div id="dialog_box">
	</div>
    	<div id="footer_text">
		<span>© <?php echo date("Y") ?> Evan Williams Consulting, LLC</span>
    	</div>
    </div>
</body>
</html>
