<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <link href="/resources/css/axure_rp_page.css" type="text/css" rel="stylesheet"/>
    <link href="/data/styles.css" type="text/css" rel="stylesheet"/>
    <link href="/files/home/styles.css" type="text/css" rel="stylesheet"/>
    <script src="/resources/scripts/jquery-1.7.1.min.js"></script>
    <script src="/resources/scripts/jquery-ui-1.8.10.custom.min.js"></script>
    <script src="/js/tinymce/tinymce.min.js"></script>
    <script src="/js/nhpress.js"></script>
    <script type="text/javascript">
      $axure.utils.getTransparentGifPath = function() { return '/resources//images/transparent.gif'; };
      $axure.utils.getOtherPath = function() { return '/resources/Other.html'; };
      $axure.utils.getReloadPath = function() { return '/resources/reload.html'; };
    </script>
<script type="text/javascript">
        tinymce.init({
            selector: "#wordarea"
        });
        tinymce.init({
            selector: "#wordage > label > textarea"
        });

    </script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5106157-2', 'auto');
  ga('send', 'pageview');

</script>
  </head>
  <body>
    <div id="base" class="">
      <!-- Unnamed (Shape) -->
      <div id="u0" class="ax_shape">
        <img id="u0_img" class="img " src="/images/home/u0.png"/>
        <!-- Unnamed () -->
        <div id="u1" class="text">
          <p><span></span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u2" class="ax_h1">
        <!-- Unnamed () -->
        <div id="u3" class="text">
          <p><span style="text-decoration:underline;">New Holland Press</span></p>
        </div>
      </div>

      <!-- Unnamed (Image) -->
      <div id="u4" class="ax_image">
        <img id="u4_img" class="img " src="/images/home/u4.jpg"/>
        <!-- Unnamed () -->
        <div id="u5" class="text">
          <p><span></span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u6" class="ax_paragraph">
        <!-- Unnamed () -->
        <div id="u7" class="text">
          <p><span>A Paper of Discussion</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u8" class="ax_paragraph">
        <!-- Unnamed () -->
        <div id="u9" class="text">
          <p><span>Saturday, August 1st, 2015</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u10" class="ax_paragraph">
        <!-- Unnamed () -->
        <div id="u11" class="text"><?php echo $this->layout()->user_toolbar; ?></div>        
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u12" class="ax_shape">
        <img id="u12_img" class="img " src="/images/home/u12.png"/>
        <!-- Unnamed () -->
        <div id="u13" class="text">
          <p><span></span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u14" class="ax_h1">
        <div id="u15" class="text">
          <p><span onclick="clickLogin()">Login!</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u16" class="ax_h1">
        <!-- Unnamed () -->
        <div id="u17" class="text">
          <p><span>Issues</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u18" class="ax_h1">
        <!-- Unnamed () -->
        <div id="u19" class="text">
          <p><span>Write!</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u20" class="ax_h1">
        <!-- Unnamed () -->
        <div id="u21" class="text">
          <p><span>Advertise!</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u22" class="ax_h1">
        <!-- Unnamed () -->
        <div id="u23" class="text">
          <p><span>Store</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u24" class="ax_h1">
        <!-- Unnamed () -->
        <div id="u25" class="text">
          <p><span>About</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u26" class="ax_h1">
        <!-- Unnamed () -->
        <div id="u27" class="text">
          <p><span>Contact</span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u28" class="sidebar">
        <!-- Unnamed () -->
        <div id="sidebar">
      	  	<div id="loginBox"></div>
      	</div>
        <div id="u29" class="text">
          <p><span></span></p>
        </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u30" class="ax_shape">
      	  <div id="content">
          	<p><span><?php echo $this->content; ?></span></p>
         </div>
      </div>

      <!-- Unnamed (Shape) -->
      <div id="u32" class="ax_shape">
        <img id="u32_img" class="img " src="/images/home/u32.png"/>
        <!-- Unnamed () -->
        <div id="u33" class="text">
          <p><span></span></p>
        </div>
      </div>


      <!-- Unnamed (Shape) -->
      <div id="u34" class="ax_h1">
        < Unnamed () ->
        <div id="u35" class="text">
          <p><span>Copyright 2015 New Holland Press</span></p>
        </div>
      </div>        
    </div>
  </body>
</html>
