<div>
	<h2>Content</h2>
	<?php
	    echo $this->form()->openTag($form);
	    echo $this->formHidden($form->get('id'));
	    ?>
		<label><span>Wordage</span><textarea id="wordarea" name="wordage" rows='8' cols='60'></textarea></label><label>
            <br/>
	    <?php
            echo $this->formRow($form->get('columnSize'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
	?>
</div>
