<div>
	<h2>Content</h2>
	<?php
	    echo $this->form()->openTag($form);
	    echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('width'));
            echo $this->formRow($form->get('height'));
            echo $this->formRow($form->get('caption'));
            echo $this->formRow($form->get('credit'));
            echo $this->formRow($form->get('picture'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
	?>
</div>
